- name: Common task for autosave module
  include_role: 
    name: ansible-role-epics-base
    tasks_from: module_common
  with_items:
    - "{{ epics_autosave_module }}"
  loop_control:
    loop_var: module

- name: Configure release for autosave module
  include_role: 
    name: ansible-role-epics-base
    tasks_from: module_configure_release
  with_items:
    - "{{ epics_autosave_module }}"
  loop_control:
    loop_var: module

- name: Make autosave module
  include_role: 
    name: ansible-role-epics-base
    tasks_from: module_make
  with_items:
    - "{{ epics_autosave_module }}"
  loop_control:
    loop_var: module
